// libSealGo.h -- C API for SealGo encryption library
// Auto-generated by Go build, with manual additions. See embed/export.go.
//
// Build:
//   CGO_ENABLED=1 go build -buildmode=c-shared -o libSealGo.so ./embed/

#ifndef LIBSEALGO_H
#define LIBSEALGO_H

#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

// sealgo_keypair holds hex-encoded X25519 keys (each 64 hex chars + NUL).
typedef struct {
    char* public_hex;   // 65 bytes (64 hex + NUL), free with sealgo_free_keypair
    char* private_hex;  // 65 bytes (64 hex + NUL)
} sealgo_keypair;

// sealgo_result holds a hex-encoded output string or an error message.
typedef struct {
    char* data;   // hex-encoded output, or NULL on error (free with sealgo_free_result)
    char* error;  // error message, or NULL on success
} sealgo_result;

// --- Key generation ---

// Generate a new X25519 keypair. Caller must free with sealgo_free_keypair.
extern void sealgo_generate_keypair(sealgo_keypair* out);

// Free a keypair allocated by sealgo_generate_keypair.
extern void sealgo_free_keypair(sealgo_keypair* kp);

// --- Hex-data API ---

// Encrypt hex-encoded data to a recipient public key.
//   dataHex: hex-encoded plaintext
//   recipientPubkeyHex: hex-encoded X25519 public key (64 hex chars)
//   out: result struct (data = hex-encoded ciphertext on success)
extern void sealgo_encrypt(const char* dataHex, const char* recipientPubkeyHex, sealgo_result* out);

// Decrypt hex-encoded data with an identity private key.
//   dataHex: hex-encoded ciphertext
//   identityPrivkeyHex: hex-encoded X25519 private key (64 hex chars)
//   out: result struct (data = hex-encoded plaintext on success)
extern void sealgo_decrypt(const char* dataHex, const char* identityPrivkeyHex, sealgo_result* out);

// Inspect an encrypted file header (no key required).
//   dataHex: hex-encoded encrypted data
//   out: result struct (data = text description on success)
extern void sealgo_inspect(const char* dataHex, sealgo_result* out);

// --- File API ---

// Encrypt a file to a recipient public key.
//   inputPath: path to input file
//   outputPath: path for encrypted output
//   recipientPubkeyHex: hex-encoded X25519 public key (64 hex chars)
//   out: result struct (error set on failure)
extern void sealgo_encrypt_file(const char* inputPath, const char* outputPath, const char* recipientPubkeyHex, sealgo_result* out);

// Decrypt a file with an identity private key.
//   inputPath: path to encrypted file
//   outputPath: path for decrypted output
//   identityPrivkeyHex: hex-encoded X25519 private key (64 hex chars)
//   out: result struct (error set on failure)
extern void sealgo_decrypt_file(const char* inputPath, const char* outputPath, const char* identityPrivkeyHex, sealgo_result* out);

// --- Version ---

// Get the library version as a string (e.g. "SealGo/__VERSION__").
// Returned string must be freed by caller.
extern char* sealgo_version_string(void);

// --- Memory ---

// Free a result struct allocated by encrypt/decrypt/inspect.
extern void sealgo_free_result(sealgo_result* res);

// Securely zero memory.
//   ptr: pointer to memory to wipe
//   length: number of bytes to zero
extern void sealgo_wipe_bytes(void* ptr, int length);

#ifdef __cplusplus
}
#endif

#endif /* LIBSEALGO_H */